### PR TITLE
Execution events: pass in results of command

### PR DESCRIPTION
**Pull request by mms-uret**
Hi,

A proposal to enhance the execution events of the commands:

Passing the result to the execution event handler would allow us to implement commands which feature some kind of "stale cache", where the fallback returns the last successful result of the command.

Cheers from Switzerland,
Urban

### CODE REVIEW

**Comment by lcf** [comment]
Hi @mms-uret. sorry it's taking so long to respond. I'm a little confused by the use case, could you give an example perhaps?

**Comment by mms-uret** [comment]
Hi @lcf,

Sure, here is a command we're now using:

```PHP
class StaleCachingCommand extends AbstractCommand
{
    protected function processExecutionEvent($eventName, $result = null)
    {
        if ($eventName == self::EVENT_SUCCESS && $result) {
            $this->cache->save($this->getCacheKey(), $result);
        }
    }

    protected function getFallback()
    {
        $result = null;
        if ($this->cache->contains($this->getCacheKey())) {
            $result = $this->cache->fetch($this->getCacheKey());
        }

        return $result;
    }
}
```

$this->cache in in this case a DoctrineCacheInterface which stores the last successful result of the command.

Like this, if a web service gets unresponsive, we can still serve the last known result from the web service.

**Comment by lcf** [comment]
It can be achieved as follows:

```php
use Odesk\Phystrix\AbstractCommand;

abstract class FallbackCacheCommand extends AbstractCommand
{
    /**
     * Implement in your commands. Successful result will be cached
     */
    abstract protected function runBase();

    private function cacheSuccessfulResult($result) {
      $this->cache->save($this->getCacheKey(), $result);
    }

    protected function run()
    {
        $result = $this->runBase();
        $this->cacheSuccessfulResult($result);
        return $result;
    }

    protected function getFallback()
    {
        $result = null;
        if ($this->cache->contains($this->getCacheKey())) {
            $result = $this->cache->fetch($this->getCacheKey());
        }

        return $result;
    }
}
```

Did I get the idea correctly? Is this solely a matter of code organization that you think would be more convenient?

**Comment by mms-uret** [comment]
Ah yes, you're right. Didn't think about that :/ Yep, in this case there's no need for the result in the event handler functions.

**Pull request closed without merging**
